library(quantmod)
library(TTR)
library(R6)
library(PerformanceAnalytics)

# strategy_func is a function that receives data as xts object
# and returns xts object of signals
calculate_strategy <- function(strategy_func, data) {
  signals <- strategy_func(data)
  return(signals)
}

SampleData <- R6Class(
  "SampleData",
  list(
    tickerData = "xts",
    in_sd = "character",
    in_ed = "character",
    out_sd = "character",
    out_ed = "character",
    # fields generated by class methods
    in_sample_data = "xts",
    out_of_sample_data = "xts",
    
    initialize = function(tickerData,
                          in_sd,
                          in_ed,
                          out_sd,
                          out_ed) {
      self$tickerData <- tickerData
      self$in_sd <- in_sd
      self$in_ed <- in_ed
      self$out_sd <- out_sd
      self$out_ed <- out_ed
      
      self$populate_sample_data()
    },
    populate_sample_data = function() {
      self$in_sample_data <- window(self$tickerData,
                                    start = self$in_sd,
                                    end = self$in_ed)
      self$out_of_sample_data <- window(self$tickerData,
                                        start = self$out_sd,
                                        end = self$out_ed)
    },
    calculate_strategy_on_in_sample = function(strategy_func) {
      return(calculate_strategy(strategy_func,
                                self$in_sample_data))
    },
    calculate_strategy_on_out_of_sample = function(strategy_func) {
      return(calculate_strategy(strategy_func,
                                self$out_of_sample_data))
    }
  )
)

StrategySummarizer <- R6Class(
  "StrategySummarizer",
  c(
    tickerData = "xts",
    signals = "xts",
    returns = "xts",
    trade_returns = "xts",
    
    initialize = function(tickerData, signals) {
      self$tickerData <- tickerData
      self$signals <- signals
      
      self$returns <-
        Delt(self$tickerData)
      self$returns[1] <- 0
      self$trade_returns <-
        self$returns * lag(self$signals)
    },
    print = function(str1, str2) {
      cat(str1, ": ", str2, "\n", sep = "")
    },
    summarize = function() {
      #cum_returns <- Return.cumulative(self$trade_returns)
      annual_returns <- Return.annualized(self$trade_returns)
      max_drawdown <- maxDrawdown(self$trade_returns)
      #daily_std_dev <- StdDev(self$trade_returns)
      annual_std_dev <- StdDev.annualized(self$trade_returns)
      val_at_risk <- VaR(self$trade_returns)
      annual_sharpe <- SharpeRatio.annualized(self$trade_returns)
      
      self$print("Annual Return", annual_returns)
      self$print("Max Drawdown", max_drawdown)
      self$print("Annual Std Deviation", annual_std_dev)
      self$print("Value At Risk at 95% Confidence", val_at_risk)
      self$print("Annual Sharpe Ratio", annual_sharpe)
    },
    plot = function() {
      charts.PerformanceSummary(self$trade_returns)
    }
  )
)

momentum_strategy_1 <- function(data) {
  macd <- MACD(
    data,
    nFast = 12,
    nSlow = 26,
    nSig = 9,
    maType = "SMA",
    percent = F
  )
  
  bb <-
    BBands(data,
           n = 20,
           maType = "SMA",
           sd = 2)
  
  signal <-
    ifelse(
      data > bb$up &
        macd$macd > macd$signal,
      1,
      ifelse(data < bb$dn &
               macd$macd < macd$signal, -1,
             0)
    )
  
  signal <- na.omit(signal)
  
  return(signal)
}

getTicker <- function(symbol, start, end) {
  data <-
    getSymbols(symbol,
               src = "yahoo",
               auto.assign = F)
  
  data <- window(data,
                 start = start,
                 end = end)
  
  # uses adjusted prices
  data <- Ad(data)
  
  # forward fill NA
  data <- na.locf(data)
  
  names(data)[1] <- "adj"
  
  return(data)
}

Nifty <- getTicker("^NSEI", "2010-01-01", "2019-12-31")

NiftySampleData <- SampleData$new(
  tickerData = Nifty,
  in_sd = "2010-01-01",
  in_ed = "2017-12-31",
  out_sd = "2018-01-01",
  out_ed = "2019-12-31"
)

in_sample_signals <-
  NiftySampleData$calculate_strategy_on_in_sample(momentum_strategy_1)

strat <- StrategySummarizer$new(Nifty, in_sample_signals)
cat("In sample Data:")
strat$summarize()

out_sample_signals <-
  NiftySampleData$calculate_strategy_on_out_of_sample(momentum_strategy_1)

strat2 <- StrategySummarizer$new(Nifty, out_sample_signals)
cat("Out of sample Data:")
strat2$summarize()

