library(quantmod)
library(TTR)
library(PerformanceAnalytics)

# strategy_func is a function that receives data as xts object
# and returns xts object of signals
calculate_strategy <- function(strategy_func, data) {
  signals <- strategy_func(data)
  return(signals)
}

SampleData <- setRefClass(
  "SampleData",
  fields = list(
    data = "xts",
    in_sd = "character",
    in_ed = "character",
    out_sd = "character",
    out_ed = "character",
    # fields generated by class methods
    in_sample_data = "xts",
    out_of_sample_data = "xts"
  ),
  methods = list(
    # must call this method first before other methods which use
    # in_sample_data or out_of_sample_data
    populate_sample_data = function() {
      in_sample_data <<- window(data,
                                start = in_sd,
                                end = in_ed)
      out_of_sample_data <<- window(data,
                                    start = out_sd,
                                    end = out_ed)
    },
    calculate_strategy_on_in_sample = function(strategy_func) {
      return(calculate_strategy(strategy_func,
                                in_sample_data))
    },
    calculate_strategy_on_out_of_sample = function(strategy_func) {
      return(calculate_strategy(strategy_func,
                                out_of_sample_data))
    }
  )
)

momentum_strategy_1 <- function(data) {
  macd <- MACD(
    data,
    nFast = 12,
    nSlow = 26,
    nSig = 9,
    maType = "SMA",
    percent = F
  )
  
  bb <-
    BBands(data,
           n = 20,
           maType = "SMA",
           sd = 2)
  
  signal <-
    ifelse(
      data > bb$up &
        macd$macd > macd$signal,
      1,
      ifelse(data < bb$dn &
               macd$macd < macd$signal,-1,
             0)
    )
  
  signal <- na.omit(signal)
  
  return(signal)
}

getTicker <- function(symbol, start, end) {
  data <-
    getSymbols(symbol,
               src = "yahoo",
               auto.assign = F)
  
  data <- window(data,
                 start = start,
                 end = end)
  
  # uses adjusted prices
  data <- Ad(data)
  
  # forward fill NA
  data <- na.locf(data)
  
  names(data)[1] <- "adj"
  
  return(data)
}

get_returns <- function(data) {
  returns <- Delt(data)
  returns[1] <- 0
  return(returns)
}

Nifty <- getTicker("^NSEI", "2010-01-01", "2019-12-31")
Nifty$returns <- get_returns(Nifty)

NiftySampleData <- SampleData$new(
  data = Nifty,
  in_sd = "2010-01-01",
  in_ed = "2017-12-31",
  out_sd = "2018-01-01",
  out_ed = "2019-12-31"
)

NiftySampleData$populate_sample_data()

in_sample_signals <-
  NiftySampleData$calculate_strategy_on_in_sample(momentum_strategy_1)

in_sample_returns <-
  Nifty_returns * lag(in_sample_signals)

in_sample_returns <- na.omit(in_sample_returns)

Return.cumulative(in_sample_returns)


